### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by yuu2lee4** [An0nymous0/rdm-mac#1]
![image](https://user-images.githubusercontent.com/8046366/56780206-00e12a80-6811-11e9-9f17-2883b9dd1a21.png)

**Comment by An0nymous0** [comment]
我的Mac 版本10.14.4 (18E226)
![image](https://user-images.githubusercontent.com/6836030/56781109-831f1e00-6814-11e9-9f8d-c78f3659e166.png)

**Comment by yuu2lee4** [comment]
一样

**Comment by lyswco** [comment]
一样报错， 10.14.4

**Comment by An0nymous0** [comment]
看一下下边的日志，可能是openssl版本的事

**Comment by ty850454** [comment]
一样不能用

**Comment by An0nymous0** [comment]
![image](https://user-images.githubusercontent.com/6836030/61511241-a7ac2000-aa28-11e9-872a-d40de9fdd552.png)
看一下本地是否有python3.7

**Comment by lilao6** [comment]
一样

**Comment by WingGao** [comment]
报错 Reason: image not found 无法打开
